name: time_formatter
description: Format timestamps like YouTube
version: 1.0.0+2
author: Jeremi Gendron <gendronjeremi@gmail.com>
homepage: https://github.com/jeremigendron
repository: https://github.com/jeremigendron/time_formatter
issue_tracker: https://github.com/jeremigendron/time_formatter/issues
documentation: https://github.com/jeremigendron/time_formatter/tree/master/README.md

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.5.3
